### PR TITLE
Basic Refactoring: Type Annotations, Final & Const Usage

### PR DESCRIPTION
**Pull request by Marc-R2**
This PR introduces some basic refactoring to improve code readability and maintainability:

- Added type annotations where possible for better static typing
- Replaced variables with `final` where applicable to ensure immutability
- Used `const` for constant values (optimize performance)

These changes don't affect the functionality of the package but should improve the overall code quality.

I will continue to break down the larger changes into smaller PRs for easier review and integration.

Thanks!

### CODE REVIEW

**Comment by lamnhan066** [comment]
Hi @Marc-R2

Please let me know if a package or your opinion suggests those changes?

I'm on the way to find a package that has better suggestions than regular `lints` so we have better code even when adding new code.

**Comment by Marc-R2** [comment]
@lamnhan066

These changes are based on some lint-rules from the [very_good_analysis 6.0.0](https://pub.dev/packages/very_good_analysis) ([rules](https://github.com/VeryGoodOpenSource/very_good_analysis/blob/main/lib/analysis_options.6.0.0.yaml)) package.

I like this package, but sometimes some of the rules are a bit harsh. I usually disable (or ignore) at least `avoid_print`, `comment_references` and `no_duplicate_case_values`. 
In my experience, code with these lints is very consistent, easy to read, and prevents many compile-time bugs.

I would be happy to add more of these lints if you want.

**Comment by lamnhan066** [comment]
Thank you. 

I’ll merge your code and add the `very_good_analysis` as a dependency after reviewed and all the tests are passed. Sometimes the compiled Worker will have unexpected behaviors when we use a static type instead of a dynamic one.

**Review by lamnhan066 — CHANGES_REQUESTED** [review]

**Comment by lamnhan066** [comment]
LGTM!

Thank you for your contributions.

**Pull request merged**
